import styles from "./Features.module.css";
import ImageUploader from "../components/ImageUploader";
import { useState } from "react";
import { IoReturnUpBack } from "react-icons/io5";
import axios from "axios";

export default function Features() {
  const [selectedImage, setSelectedImage] = useState(null);
  const [prediction, setPrediction] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleFileSelect = (file) => {
    setSelectedImage(file);
  };

  const handleSubmit = () => {
    setIsLoading(true);
    // Create form data
    const formData = new FormData();
    if (typeof selectedImage === "string") {
      formData.append("filepath", selectedImage.split("/").pop()); // Only send the filename
    } else {
      formData.append("file", selectedImage);
    }

    // Send image to server for prediction
    axios
      .post("http://localhost:8000/upload", formData)
      .then((response) => {
        console.log(response.data);

        setTimeout(() => {
          setIsLoading(false);
          setPrediction(response.data.message);
        }, 2000);
      })
      .catch((error) => {
        console.error("Error uploading image:", error);
        alert(error.response?.data?.error || "Error uploading image");
        setIsLoading(false);
      });
  };

  const handleCancel = () => {
    setSelectedImage(null);
    setPrediction(null);
  };
  return (
    <div className={styles.features}>
      <div className={styles.leftFlex}>
        <h1>Is it AI or Not Ah?!</h1>
        <p>
          Determine whether an image has been generated by artificial
          intelligence or a human
        </p>
        <div className={styles.sampleImages}>
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-02.jpg"
            alt="Sample 1"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-02.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-05.jpg"
            alt="Sample 2"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-05.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-07.jpg"
            alt="Sample 3"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-07.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-08.jpg"
            alt="Sample 4"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-08.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-11.jpg"
            alt="Sample 5"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-11.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-12.jpg"
            alt="Sample 6"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-12.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-14.jpg"
            alt="Sample 7"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-14.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-16.jpg"
            alt="Sample 8"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-16.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-18.jpg"
            alt="Sample 9"
            className={styles.image}
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-18.jpg")}
          />
          <img
            src="http://localhost:8000/static/photo_2023-08-17_23-10-20.jpg"
            onClick={() => setSelectedImage("photo_2023-08-17_23-10-20.jpg")}
            alt="Sample 10"
            className={styles.image}
          />
        </div>
      </div>
      <div className={styles.rightFlex}>
        {isLoading && (
          <div className={styles.progressBar}>
            <div></div>
          </div>
        )}
        {!isLoading &&
          (selectedImage ? (
            <div className={styles.imageWrapper}>
              <button onClick={handleCancel} className={styles.cancelButton}>
                <IoReturnUpBack size={20} />
              </button>
              <img
                src={
                  typeof selectedImage === "string"
                    ? selectedImage
                    : URL.createObjectURL(selectedImage)
                }
                alt="Uploaded Preview"
                className={styles.uploadedImage}
              />
            </div>
          ) : (
            <ImageUploader onFileSelect={handleFileSelect} />
          ))}

        <button
          className={styles.btn}
          onClick={handleSubmit}
          disabled={!selectedImage || isLoading}
        >
          Submit
        </button>
        {prediction && (
          <p
            className={`${styles.predictionResult} ${
              prediction === "Human Generated"
                ? styles.humanGenerated
                : styles.notHumanGenerated
            }`}
          >
            This image is {prediction}
          </p>
        )}
      </div>
    </div>
  );
}
