import styles from "./Features.module.css";
import ImageUploader from "../components/ImageUploader";
import { useState } from "react";
import { IoReturnUpBack } from "react-icons/io5";

export default function Features() {
  const [selectedImage, setSelectedImage] = useState(null);
  const handleFileSelect = (file) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      setSelectedImage(reader.result);
    };
    reader.readAsDataURL(file);
  };
  const handleSubmit = () => {
    if (!selectedImage) {
      alert("Please select an image first.");
      return;
    }
    // Here, you can perform the submission logic, like uploading to a server.
    console.log("Submitting the image...");
    // For now, we're just using an alert to indicate the submission.
    alert("Image submitted!");
  };
  const handleCancel = () => {
    setSelectedImage(null);
  };
  return (
    <div className={styles.features}>
      <div className={styles.leftFlex}>
        <h1>Is it AI or Not Ah?!</h1>
        <p>
          Determine whether an image has been generated by artificial
          intelligence or a human
        </p>
        <div className={styles.sampleImages}>
          <img
            src="photo_2023-08-17_23-10-02.jpg"
            alt="Sample 1"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-05.jpg"
            alt="Sample 2"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-07.jpg"
            alt="Sample 3"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-08.jpg"
            alt="Sample 4"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-11.jpg"
            alt="Sample 5"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-12.jpg"
            alt="Sample 6"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-14.jpg"
            alt="Sample 7"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-16.jpg"
            alt="Sample 8"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-18.jpg"
            alt="Sample 9"
            className={styles.image}
          />
          <img
            src="photo_2023-08-17_23-10-20.jpg"
            alt="Sample 10"
            className={styles.image}
          />
        </div>
      </div>
      <div className={styles.rightFlex}>
        {selectedImage ? (
          <div className={styles.imageWrapper}>
            <button onClick={handleCancel} className={styles.cancelButton}>
              <IoReturnUpBack size={20} />
            </button>
            <img
              src={selectedImage}
              alt="Uploaded Preview"
              className={styles.uploadedImage}
            />
          </div>
        ) : (
          <ImageUploader onFileSelect={handleFileSelect} />
        )}
        <button
          className={styles.btn}
          onClick={handleSubmit}
          disabled={!selectedImage}
        >
          Submit
        </button>
      </div>
    </div>
  );
}
